name: Keep Alive

on:
  schedule:
    - cron: '0 0 */20 * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Keep alive
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          date > .github/keepalive.txt

          git add .
          git commit -m "keep alive" || echo "No changes"

          git push